version: '3.3'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3003:8080'
    volumes:
      - '/app/node_modules'
      - './:/app'
